### ISSUE TITLE
Functional test using raw files (autoQC01) from different LC-MS systems @FGCZ 

### ISSUE THREAD

**Issue by cpanse** [fgcz/rawR#11]
# determine input 

last two files of each available instrument
```{bash}
PFILE=/srv/www/htdocs/Data2San/sync_LOGS/pfiles.txt ; 
cat ${PFILE} \
  | cut -f4 -d";" \
  | cut -d"/" -f3 \
  | sort \
  | uniq \
  |while read i ; 
  do 
        grep -E "/${i}/.*autoQC01.*raw$" ${PFILE} \
          | tail -n 2; 
  done \
  | cut -d";" -f4 \
  | while read raw ; 
    do 
        [[ -f /srv/www/htdocs/${raw} ]] && echo ${raw} ; 
  done
```

**Comment by tobiasko** [comment]
Sorry, had to change that issue title. ;-)

**Comment by tobiasko** [comment]
Could you build a webpage for the output? That would be really cool. Our own little test environment!

**Comment by tobiasko** [comment]
That would also be a cool extension for our case II, far too big for the manuscript, but we could put the link in the text!

**Comment by cpanse** [comment]
https://fgcz-ms.uzh.ch/~cpanse/rawR/test/functional_test.html

**Comment by cpanse** [comment]
mission completed
