### ISSUE TITLE
make generic plotting function for spectrum objects

### ISSUE THREAD

**Issue by tobiasko** [fgcz/rawR#8]
Implementation of `plot.rawRspectrum(...)` assuming  `$class = "rawRspectrum"`

**Comment by tobiasko** [comment]
I added a first draft of a `plot.rawRspectrum()` function yesterday. I realized we still need the following attributes in rawRspectrum for better plotting:

- Total Ion Current
- Scan Low Mass
- Scan High Mass
- Base Peak Intensity
- Base Peak Mass

once these become available I would add options/parameters for relative/abs. plotting and further visualizations for centroid attributes. Talking of centroid attributes. The peak resolution is also still missing, as well as peak flags.

**Comment by cpanse** [comment]
```
R> S[[1]]$massRange
[1]  350 1800
R> S[[1]]$TIC
[1] 78725448
R> S[[1]]$basePeak
[1]     445.1181 5979308.0000
```

**Comment by tobiasko** [comment]
Just Pushed a new plot function to repo that uses proper xlims and is capable of relative and abs. plotting.

**Comment by tobiasko** [comment]
I just added a peak labeling for the most intense peak in `plot.rawRspectrum(centroid = TRUE, legend = FALSE)`:

![image](https://user-images.githubusercontent.com/12233339/96790039-71610b80-13f6-11eb-8e30-8170498c2f48.png)

Problems:

- We are still missing the Resolution of centroided peaks, so I can't add it.
- Not sure how to best place the legend relative to the peaks (they easily end up outside the plot region. Maybe you have a better idea, @cpanse!

**Comment by cpanse** [comment]
![plotSN-1](https://user-images.githubusercontent.com/4901987/97789921-99095e00-1bc4-11eb-95b4-18865af06d9d.jpg)
![plot rawRspectrum-1](https://user-images.githubusercontent.com/4901987/97789935-b2aaa580-1bc4-11eb-9b4b-6f582f9af97b.jpg)

DONE
